MDScreen:

    MDNavigationLayout:

        MDScreenManager:
            id: screen_manager

            MDScreen:
                name: "tasks"
                
                MDFloatLayout:
                    
                    MDLabel:
                        id: quest_label
                        halign: 'center'
                        markup: True
                        text: "Task Quest"
                        font_style: "H4"
                        pos_hint: {'y': 0.45}

                    MDLabel:
                        id: instructions
                        halign: 'center'
                        markup: True
                        text: "Roll the D20 at the bottom of the screen to have a task randomly generated as your quest."
                        font_style: "Body1"
                        theme_text_color: "Hint"
                        pos_hint: {'y': 0.38}

                    MDLabel:
                        id: quest_task
                        halign: 'center'
                        markup: True
                        text: ""
                        font_style: "Body1"
                        theme_text_color: "Custom"
                        text_color: app.theme_cls.accent_dark
                        pos_hint: {'y': 0.3}

                    MDLabel:
                        id: hint
                        halign: 'center'
                        text: ""
                        font_style: "Caption"
                        theme_text_color: "Hint"
                        pos_hint: {'y': 0.21}

                    MDLabel:
                        id: task_label
                        halign: 'left'
                        markup: True
                        text: "Task List"
                        font_style: "H5"
                        pos_hint: {'y': 0.18, 'x': 0.08}

                    MDScrollView:
                        pos_hint: {'center_y': 0.4, 'center_x': 0.5}
                        size_hint: 0.9, 0.5
                        MDList:
                            id: container

                    MDFloatingActionButton:
                        icon: "plus-thick"
                        on_release: app.show_tasks()
                        elevation_normal: 12
                        pos_hint: {'x': 0.35, 'y': 0.04}

                    MDFloatingActionButton:
                        icon: "dice-d20"
                        theme_icon_color: "Primary"
                        md_bg_color: app.theme_cls.accent_dark
                        on_release: app.rollForTask()
                        elevation_normal: 12
                        pos_hint: {'x': 0.55, 'y': 0.04}

<DialogContent>
    orientation: 'vertical'
    spacing: "10dp"
    size_hint: 1, None
    height: "130dp"

    GridLayout:
        rows: 2

        MDTextField:
            id: task_text
            hint_text: "Add Task ..."
            mode: "rectangle"
            pos_hint: {'center_y': 0.4}
            max_text_length: 50
            on_text_validate: (app.add_task(task_text, difficulty_text), app.close_dialog())

        MDTextField:
            id: difficulty_text
            hint_text: "Enter Difficulty (Low =1, High =5) ..."
            mode: "rectangle"
            pos_hint: {'center_y': 0.4}
            max_text_length: 1
            on_text_validate: (app.add_task(task_text, difficulty_text), app.close_dialog())
    
        
        BoxLayout:
            orientation: "horizontal"

            MDRaisedButton:
                text: "SAVE"
                on_release: (app.add_task(task_text, difficulty_text), app.close_dialog())
            
            MDFlatButton:
                text: "CANCEL"
                on_release: (app.close_dialog())

<ListItemWithCheckbox>
    id: list_task
    markup: True

    LeftCheckbox:
        id: check
        on_release: root.mark(check, list_task)
    
    IconRightWidget:
        icon: "trash-can-outline"
        theme_text_color: "Custom"
        text_color: 1, 0, 0, 1
        on_release: root.delete_item(list_task)
