MDFloatLayout:
    MDLabel:
        id: task_label
        halign: 'center'
        markup: True
        text: "Task Quest"
        font_style: "H5"
        pos_hint: {'y': 0.45}

    ScrollView:
        pos_hint: {'center_y': 0.5, 'center_x': 0.5}
        size_hint: 0.9, 0.8
        MDList:
            id: container

    MDFloatingActionButton:
        icon: "plus-thick"
        on_release: app.show_task_function()
        elevation_normal: 12
        pos_hint: {'x': 0.45, 'y': 0.04}

<DialogContent>
    orientation: 'vertical'
    spacing: "10dp"
    size_hint: 1, None
    height: "130dp"

    GridLayout:
        rows: 2

        MDTextField:
            id: task_text
            hint_text: "Add Task ..."
            mode: "rectangle"
            pos_hint: {'center_y': 0.4}
            max_text_length: 50
            on_text_validate: (app.add_task(task_text, difficulty_text), app.close_dialog())

        MDTextField:
            id: difficulty_text
            hint_text: "Enter Difficulty (Low =1, High =5) ..."
            mode: "rectangle"
            pos_hint: {'center_y': 0.4}
            max_text_length: 1
            on_text_validate: (app.add_task(task_text, difficulty_text), app.close_dialog())
    
        
        BoxLayout:
            orientation: "horizontal"

            MDRaisedButton:
                text: "SAVE"
                on_release: (app.add_task(task_text, difficulty_text), app.close_dialog())
            
            MDFlatButton:
                text: "CANCEL"
                on_release: (app.close_dialog())

<ListItemWithCheckbox>
    id: the_list_item
    markup: True

    LeftCheckbox:
        id: check
        on_release: root.mark(check, the_list_item)
    
    IconRightWidget:
        icon: "trash-can-outline"
        theme_text_color: "Custom"
        text_color: 1, 0, 0, 1
        on_release: root.delete_item(the_list_item)